services:
  # Backend NestJS API Service
  - type: web
    name: inventra-api
    env: node
    buildCommand: npm install && npx prisma generate --schema=apps/api/prisma/schema.prisma && npm run build -w apps/api
    startCommand: npx prisma db push --schema=apps/api/prisma/schema.prisma && node apps/api/dist/apps/api/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_PROVIDER
        value: resend
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: onboarding@resend.dev
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

  # Frontend Vite React Static Site
  - type: web
    name: inventra-web
    env: static
    buildCommand: npm install && npm run build -w apps/web
    staticPublishPath: apps/web/dist
